Add style
yosefHesham/book_store pull request #6
Opened 2022-06-17 20:32 UTC by yosefHesham

**Brief of what changed:**

Added styles to the bookstore to make it fancier and eye-catching.

---

**Changes Made:**

- Created progress component.
- Created chapter component.
- Created bookInfo component.

2022-06-17 20:59 UTC, ahmetbozaci requested changes
# STATUS: Changes Required  ♻️
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)

 @yosefHesham  ✋🏼 

#### Your project is great. You are almost done. However, there are some issues you should fix. Please fix them then your project will be approved.

___ 

### 💯  Nice to have 💯
- Your git-flow is correct. ✔️
- You set up linter files and no errors. ✔️
- Your pull request is very professional. It has a meaningful title and summary. Keep it up.✔️
___


### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._
- [ ] Kindly fix the broken link in the license section.
 ![image](https://user-images.githubusercontent.com/38635158/174398877-b016b4db-a8f5-4a3f-b4d4-ae8b303592bc.png)


___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
___

### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._


___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-06-17 20:59 UTC, ahmetbozaci commented on src/App.css
> +  display: flex;
- [ ] For DRY CSS you should combine duplicate properties. 
Example, you can create class `.d-flex { display: flex}` and use this class in HTML file.
### _This is just one example. Please check your CSS file and if some CSS rules are the same please combine them also._
- [More information about DRY principles](https://www.freecodecamp.org/news/7-important-tips-for-writing-better-css/) 

- [Html and CSS best practices in curriculum](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md#:~:text=If%20you%20want%20to%20create%20a%20CSS%20rule%20for%20multiple%20elements%2C%20use%20a%20class%20attribute%20instead.%20For%20example%2C%20instead%20of%20using%20color%3A%20%233498db%3B%203%20times)

2022-06-17 20:59 UTC, ahmetbozaci commented on src/components/navbar.js
> +        <h1> Bookstore CMS </h1>
- [ ] The navigation bar is different than the original. To stick to the design kindly fix it.

![image](https://user-images.githubusercontent.com/38635158/174399386-0d63930f-2ec1-4641-8c5e-49de1c5d37b3.png)

___
ORIGINAL
![image](https://user-images.githubusercontent.com/38635158/174399427-1a00882f-35cb-45f7-8e04-8643d15d085a.png)

2022-06-17 20:59 UTC, ahmetbozaci commented on src/components/add_book.js
> +    </>
- [ ] The form is different from the original. It is ok if you add author input but please add category input also.
- [ ] Please align the form to the book list.
- [ ] Please change the update progress button style like in the original.

![image](https://user-images.githubusercontent.com/38635158/174399893-57548124-daec-4fd5-adc3-3951b3fdf433.png)
__
Original
![image](https://user-images.githubusercontent.com/38635158/174399951-7c63df7b-a7a0-43e5-957b-9825f3187c53.png)

2022-06-18 20:37 UTC, zieeco approved these changes
# status: APPROVED :green_circle: :100: 

Hi, @yosefHesham , 


![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/164945882-0a9554ea-956c-4fa0-a95c-379285283c1d.gif)


Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡
 
✅ Descriptive PR 👍 
✅ Nice design 🔥 
✅ Good commit messages 👍 
✅ Linters are passing 👏 


## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-18 20:40 UTC, merged